name: Azure Login via FIC

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Azure using Federated Identity Credential
      uses: azure/login@v1
      with:
        client-id: '9743933c-6bb5-4aca-847f-57e299df1689'
        tenant-id: '9743933c-6bb5-4aca-847f-57e299df1689'
        allow-no-subscriptions: true

    - name: Verify Azure login
      run: az account show
